./vegeta attack -header "Content-Type: application/json" -rate=617/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_1.json
./vegeta attack -header "Content-Type: application/json" -rate=591/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_2.json
./vegeta attack -header "Content-Type: application/json" -rate=612/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_3.json
./vegeta attack -header "Content-Type: application/json" -rate=622/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_4.json
./vegeta attack -header "Content-Type: application/json" -rate=755/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_5.json
./vegeta attack -header "Content-Type: application/json" -rate=1079/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_6.json
./vegeta attack -header "Content-Type: application/json" -rate=1062/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_7.json
./vegeta attack -header "Content-Type: application/json" -rate=1055/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_8.json
./vegeta attack -header "Content-Type: application/json" -rate=1028/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_9.json
./vegeta attack -header "Content-Type: application/json" -rate=1043/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_10.json
./vegeta attack -header "Content-Type: application/json" -rate=1025/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_11.json
./vegeta attack -header "Content-Type: application/json" -rate=1053/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_12.json
./vegeta attack -header "Content-Type: application/json" -rate=1053/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_13.json
./vegeta attack -header "Content-Type: application/json" -rate=994/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_14.json
./vegeta attack -header "Content-Type: application/json" -rate=1027/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_15.json
./vegeta attack -header "Content-Type: application/json" -rate=1028/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_16.json
./vegeta attack -header "Content-Type: application/json" -rate=1016/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_17.json
./vegeta attack -header "Content-Type: application/json" -rate=1055/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_18.json
./vegeta attack -header "Content-Type: application/json" -rate=1014/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_19.json
./vegeta attack -header "Content-Type: application/json" -rate=1090/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_20.json
./vegeta attack -header "Content-Type: application/json" -rate=917/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_21.json
./vegeta attack -header "Content-Type: application/json" -rate=1025/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_22.json
./vegeta attack -header "Content-Type: application/json" -rate=1036/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_23.json
./vegeta attack -header "Content-Type: application/json" -rate=932/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_24.json
./vegeta attack -header "Content-Type: application/json" -rate=925/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_25.json
./vegeta attack -header "Content-Type: application/json" -rate=874/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_26.json
./vegeta attack -header "Content-Type: application/json" -rate=750/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_27.json
./vegeta attack -header "Content-Type: application/json" -rate=680/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_28.json
./vegeta attack -header "Content-Type: application/json" -rate=640/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_29.json
./vegeta attack -header "Content-Type: application/json" -rate=660/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_30.json
./vegeta attack -header "Content-Type: application/json" -rate=624/1m -duration=1m -targets=ptargs_masks.txt | ./vegeta encode > logs/results_31.json
