./vegeta attack -header "Content-Type: application/json" -rate=30/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_1.json
./vegeta attack -header "Content-Type: application/json" -rate=29/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_2.json
./vegeta attack -header "Content-Type: application/json" -rate=30/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_3.json
./vegeta attack -header "Content-Type: application/json" -rate=31/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_4.json
./vegeta attack -header "Content-Type: application/json" -rate=37/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_5.json
./vegeta attack -header "Content-Type: application/json" -rate=53/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_6.json
./vegeta attack -header "Content-Type: application/json" -rate=53/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_7.json
./vegeta attack -header "Content-Type: application/json" -rate=52/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_8.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_9.json
./vegeta attack -header "Content-Type: application/json" -rate=52/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_10.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_11.json
./vegeta attack -header "Content-Type: application/json" -rate=52/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_12.json
./vegeta attack -header "Content-Type: application/json" -rate=52/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_13.json
./vegeta attack -header "Content-Type: application/json" -rate=49/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_14.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_15.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_16.json
./vegeta attack -header "Content-Type: application/json" -rate=50/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_17.json
./vegeta attack -header "Content-Type: application/json" -rate=52/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_18.json
./vegeta attack -header "Content-Type: application/json" -rate=50/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_19.json
./vegeta attack -header "Content-Type: application/json" -rate=54/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_20.json
./vegeta attack -header "Content-Type: application/json" -rate=45/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_21.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_22.json
./vegeta attack -header "Content-Type: application/json" -rate=51/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_23.json
./vegeta attack -header "Content-Type: application/json" -rate=46/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_24.json
./vegeta attack -header "Content-Type: application/json" -rate=46/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_25.json
./vegeta attack -header "Content-Type: application/json" -rate=43/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_26.json
./vegeta attack -header "Content-Type: application/json" -rate=37/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_27.json
./vegeta attack -header "Content-Type: application/json" -rate=34/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_28.json
./vegeta attack -header "Content-Type: application/json" -rate=32/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_29.json
./vegeta attack -header "Content-Type: application/json" -rate=33/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_30.json
./vegeta attack -header "Content-Type: application/json" -rate=31/1m -duration=1m -targets=ptargs_images.txt | ./vegeta encode > logs/results_31.json
