# Model should be placed in the prototype/models directory with an appropriate dirname
# Model name (<modelname>)
model: alexnet

# Function deployment specifications
function:
  # Deploy the function (true/false)
  deploy: "true"
  # Weight for function routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 2

# Container deployment specifications
container:
  # Deploy the container (true/false)
  deploy: "false"
  # Weight for container routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 2

# VM deployment specifications
vm:
  # Deploy the VM (true/false)
  deploy: "false"
  # Weight for VM routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 2
