# Model should be placed in the prototype/models directory with an appropriate dirname
# Model name (<modelname>)
model: alexnet

# Function deployment specifications
function:
  # Deploy the function (true/false)
  deploy: "true"
  # Weight for function routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 1

# Container deployment specifications
container:
  # Deploy the container (true/false)
  deploy: "false"
  # Weight for container routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 1
  # Do you have root access for Docker (true/false)
  rootAccess: "false"

# VM deployment specifications
vm:
  # Deploy the VM (true/false)
  deploy: "false"
  # Weight for VM routing (0 to 100)
  weight: 100
  # Instances (0 to any)
  instances: 1
  # Do you have root access for libvirt (true/false)
  rootAccess: "false"
  # Cloud-Image Directory - Place your cloud image used for the VM here
  cloudImgDir: "/var/scratch/ssundar"

# Load-balancer specifications
lb:
  # Do you have root access for Docker (true/false)
  rootAccess: "false"
